## 1. Importing the used libraries

In [1]:
import numpy as np
import pandas as pd

## 2. Read the CSV file

In [67]:
df = pd.read_csv("amazon.csv")

## 3. Viewing and inspecting data (EDA)

In [68]:
# Checking the shape
print(f"Dataset Shape: {df.shape}")

# Checking the data types and non-null counts
print("\nDataset info:")
df.info()

# Checking summary statistics
print("\nSummary Statistics:")
display(df.describe(include= "all"))

# Checking the count of missing values
print(f"\nThe count of missing values:\n{df.isnull().sum()}")

# Printing the first 5 records
print("\nThe first 5 records:")
display(df.head())

Dataset Shape: (1465, 16)

Dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   object
 4   actual_price         1465 non-null   object
 5   discount_percentage  1465 non-null   object
 6   rating               1465 non-null   object
 7   rating_count         1463 non-null   object
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
dtypes: object(16)
memory usage: 183.3+ KB

Summary Statistics:

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
count,1465,1465,1465,1465,1465,1465,1465,1463,1465,1465,1465,1465,1465,1465,1465,1465
unique,1351,1337,211,550,449,92,28,1143,1293,1194,1194,1194,1194,1212,1412,1465
top,B07JW9H4J1,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",Computers&Accessories|Accessories&Peripherals|...,₹199,₹999,50%,4.1,"9,378",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...","I am not big on camera usage, personally. I wa...",https://m.media-amazon.com/images/I/413sCRKobN...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
freq,3,5,233,53,120,56,244,9,6,10,10,10,10,8,3,1

The count of missing values:
product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           2
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

The first 5 records:

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

## 4. Data Cleaning & Wrangling

In [69]:
# Remove unnecessary characters like "₹", "%", "," from numbers and cost them to float/int

df['discounted_price'] = df['discounted_price'].str.replace('₹', '').str.replace(',', '').astype(float)
df['actual_price'] = df['actual_price'].str.replace('₹', '').str.replace(',', '').astype(float)
df['discount_percentage'] = df['discount_percentage'].str.replace('%', '').astype(float)

In [70]:
# Fixing rating and rating_count columns

df['rating'] = df['rating'].str.replace('|', '', regex=False)
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')  # it converts everything to float, and if it encounter something that cannot be converted, it replace it with "NaN" value

df['rating_count'] = df['rating_count'].str.replace(',', '')
df['rating_count'] = pd.to_numeric(df['rating_count'], errors= 'coerce')

In [71]:
# handling missing values using numpy
avg_rating = np.nanmean(df['rating'])
df['rating'] = df['rating'].fillna(avg_rating)

avg_rating_count = np.nanmean(df['rating_count'])
df['rating_count'] = df['rating_count'].fillna(avg_rating_count)

In [97]:
# Extract the main category (first item before the first '|')

df['category'] = df['category'].astype(str)
df['main_category'] = df['category'].apply(lambda x: x.split('|')[0])

In [104]:
# Now let's repeat the inspection (EDA) to see what have changed

# Checking the shape
print(f"Dataset Shape: {df.shape}")      # The columns increased by 1 "Main categories", so becoming 17 instead of 16

# Checking the data types and non-null counts
print("\nDataset info:")
df.info()        # Not all datatype is object, some has been converted into float64, and there are no missing values

# Checking summary statistics
print("\nSummary Statistics:")
display(df.describe(include= "all"))      # There is a quantitative (numerical) stats, not only qualitative (categorical)

# Checking the count of missing values
print(f"\nThe count of missing values:\n{df.isnull().sum()}")

# Printing the first 5 records
print("\nThe first 5 records:")
display(df.head())

Dataset Shape: (1465, 17)

Dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   object
 1   product_name         1465 non-null   object
 2   category             1465 non-null   object
 3   discounted_price     1465 non-null   float64
 4   actual_price         1465 non-null   float64
 5   discount_percentage  1465 non-null   float64
 6   rating               1465 non-null   float64
 7   rating_count         1465 non-null   float64
 8   about_product        1465 non-null   object
 9   user_id              1465 non-null   object
 10  user_name            1465 non-null   object
 11  review_id            1465 non-null   object
 12  review_title         1465 non-null   object
 13  review_content       1465 non-null   object
 14  img_link             1465 non-null   object
 15  product_link         1465 non-null   object
 16  main_category        1465 non-null   object
dtypes: float64(5), object(12)
memory usage: 194.7+ KB

Summary Statistics:

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link,main_category
count,1465,1465,1465,1465.000000,1465.000000,1465.000000,1465.000000,1465.000000,1465,1465,1465,1465,1465,1465,1465,1465,1465
unique,1351,1337,211,NaN,NaN,NaN,NaN,NaN,1293,1194,1194,1194,1194,1212,1412,1465,9
top,B07JW9H4J1,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",Computers&Accessories|Accessories&Peripherals|...,NaN,NaN,NaN,NaN,NaN,[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...","I am not big on camera usage, personally. I wa...",https://m.media-amazon.com/images/I/413sCRKobN...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...,Electronics
freq,3,5,233,NaN,NaN,NaN,NaN,NaN,6,10,10,10,10,8,3,1,526
mean,NaN,NaN,NaN,3125.310874,5444.990635,47.691468,4.096585,18295.541353,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,6944.304394,10874.826864,21.635905,0.291574,42724.651512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,39.000000,39.000000,0.000000,2.000000,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,325.000000,800.000000,32.000000,4.000000,1191.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,799.000000,1650.000000,50.000000,4.100000,5179.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,1999.000000,4295.000000,63.000000,4.300000,17394.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,77990.000000,139900.000000,94.000000,5.000000,426973.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

The count of missing values:
product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           0
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
main_category          0
dtype: int64

The first 5 records:

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link,main_category
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,399.0,1099.0,64.0,4.2,24269.0,High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...,Computers&Accessories
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,199.0,349.0,43.0,4.0,43994.0,"Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...,Computers&Accessories
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,199.0,1899.0,90.0,3.9,7928.0,【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...,Computers&Accessories
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,329.0,699.0,53.0,4.2,94363.0,The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...,Computers&Accessories
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,154.0,399.0,61.0,4.2,16905.0,[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...,Computers&Accessories

## 5. Feature Engineering

In [105]:
df.columns

Index(['product_id', 'product_name', 'category', 'discounted_price',
       'actual_price', 'discount_percentage', 'rating', 'rating_count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'img_link', 'product_link', 'main_category'],
      dtype='object')

In [118]:
# First, make a column called "Discount amount" which refer to the actual savings in Currency (Actual - Discounted)

df['discount_amount'] = df['actual_price'] - df['discounted_price']

# Second, make a column called "price_per_rating" which refer to price paid per rating point (Lower ratio = higher relative value for rating)

df['price_per_rating'] = np.round(df['discounted_price'] / df['rating'], 2)       # Round to two decimal numbers

# Third, make a column called "rating_tier" which categorizes products into qualitative performance buckets

conditions = [(df['rating'] >= 4.5),
             (df['rating'] >= 4.0) & (df['rating'] < 4.5),
             (df['rating'] >= 3.5) & (df['rating'] < 4.5)]

choices = ['Excellent', 'Good', 'Average']

df['rating_tier'] = np.select(conditions, choices, default='Low')       # constructs a new array by selecting elements from choices based on multiple specified conditions

print("Engineered features:")
print(df[['product_name', 'actual_price', 'discounted_price', 'discount_amount', 'rating', 'price_per_rating', 'rating_tier']].head())
print("\nDistribution of Rating Tiers:\n")
print(df['rating_tier'].value_counts())         # The count of every tier

Engineered features:
                                        product_name  actual_price  \
0  Wayona Nylon Braided USB to Lightning Fast Cha...        1099.0
1  Ambrane Unbreakable 60W / 3A Fast Charging 1.5...         349.0
2  Sounce Fast Phone Charging Cable & Data Sync U...        1899.0
3  boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...         699.0
4  Portronics Konnect L 1.2M Fast Charging 3A 8 P...         399.0

   discounted_price  discount_amount  rating  price_per_rating rating_tier
0             399.0            700.0     4.2             95.00        Good
1             199.0            150.0     4.0             49.75        Good
2             199.0           1700.0     3.9             51.03     Average
3             329.0            370.0     4.2             78.33        Good
4             154.0            245.0     4.2             36.67        Good

Distribution of Rating Tiers:

rating_tier
Good         1007
Average       312
Excellent     104
Low            42
Name: count, dtype: int64

## 6. Exploratory Data Analysis (EDA) & NumPy Business Insights

In [122]:
df.columns

Index(['product_id', 'product_name', 'category', 'discounted_price',
       'actual_price', 'discount_percentage', 'rating', 'rating_count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'img_link', 'product_link', 'main_category',
       'discount_amount', 'price_per_rating', 'rating_tier'],
      dtype='object')

In [130]:
# First core business question is about "Category Performance", Which main categories generate the highest average discounts and customer engagement?

category_summary = df.groupby('main_category').agg(
    product_count = ('product_id', 'count'),
    avg_discount_percentage = ('discount_percentage', 'mean'),
    avg_rating = ('rating', 'mean'),
    total_reviews = ('rating_count', 'sum')
).reset_index().sort_values(by = 'product_count', ascending = False).round(2)

print('The main categories performance:\n')
print(category_summary)

The main categories performance:

           main_category  product_count  avg_discount_percentage  avg_rating  \
2            Electronics            526                    50.83        4.08
1  Computers&Accessories            453                    54.02        4.15
4           Home&Kitchen            448                    40.12        4.04
7         OfficeProducts             31                    12.35        4.31
5        HomeImprovement              2                    57.50        4.25
6     MusicalInstruments              2                    46.00        3.90
0          Car&Motorbike              1                    42.00        3.80
3    Health&PersonalCare              1                    53.00        4.00
8             Toys&Games              1                     0.00        4.30

   total_reviews
2    15778848.00
1     7765280.08
4     2991069.00
7      149675.00
5        8566.00
6       88882.00
0        1118.00
3        3663.00
8       15867.00

In [145]:
# Second core business question is about "Discount vs. Rating Correlation", Do higher discounts lead to better customer ratings, or do heavily discounted items signal poor quality?

corr_matrix =  df[['discount_percentage', 'rating', 'rating_count', 'discount_amount']].corr()

print(f"Correlation Matrix:\n{corr_matrix}")

# Print specific statistical takeaway
print(f"\nThe specific correlation between (Discount % vs. Rating): {np.round(corr_matrix.iloc[0,1], 4)}")

Correlation Matrix:
                     discount_percentage    rating  rating_count  \
discount_percentage             1.000000 -0.155261      0.011676
rating                         -0.155261  1.000000      0.101397
rating_count                    0.011676  0.101397      1.000000
discount_amount                 0.086675  0.105798     -0.044230

                     discount_amount
discount_percentage         0.086675
rating                      0.105798
rating_count               -0.044230
discount_amount             1.000000

The specific correlation between (Discount % vs. Rating): -0.1553

In [150]:
# Third core business question is about "Rating Tier Revenue Impact", How are products distributed across rating tiers (Exceptional, Good, Average, Low), and what is the median total volume of reviews for each tier?

tier_summary = df.groupby('rating_tier').agg(
    total_products=('product_id', 'count'),
    median_price=('discounted_price', 'median'),
    avg_rating=('rating', 'mean'),
    median_reviews=('rating_count', 'median')
).reindex(['Excellent', 'Good', 'Average', 'Low'])

print("Summary by Rating Tier:\n")
print(tier_summary)

Summary by Rating Tier:

             total_products  median_price  avg_rating  median_reviews
rating_tier
Excellent               104         954.5    4.550962          4651.5
Good                   1007         799.0    4.186988          7113.0
Average                 312         804.0    3.778526          2171.0
Low                      42         499.0    3.166667           454.5

In [151]:
# Third core business question is about "Outlier Detection via NumPy", Identify extreme discount outliers using NumPy percentile bounds ($IQR$ method).

q75, q25 = np.percentile(df['discount_percentage'], [75, 25])
iqr = q75 - q25
upper_bound = q75 + (1.5 * iqr)
lower_bound = q25 - (1.5 * iqr)

outliers = df[df['discount_percentage'] > upper_bound]
print(f"\n--- Discount Outlier Detection ---")
print(f"Upper Bound threshold for Discount %: {upper_bound:.2f}%")
print(f"Number of Extreme Discount Outliers: {len(outliers)}")

--- Discount Outlier Detection ---
Upper Bound threshold for Discount %: 109.50%
Number of Extreme Discount Outliers: 0